---
title: "Lab 1"
author: "Haley Jeppson, Ashish Jain, Vinny Paris"
date: "January 19, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	message = FALSE,
	warning = FALSE
)
library(tidyverse)
library(viridis)

```

## Question 1
The last word on page 21 is "May"

## Question 2

#### Retrieving the Data



```{r}


tmax <- function(stationid){
  station <- paste("ushcn.v2.5.5.20170118/", stationid, ".raw.tmax", sep="")
  temps <- read_fwf(station, 
                   col_positions=  fwf_positions(
                     start=c( 1,13, rep(16+9*0:11, each=4) + c(1,7,8,9)), 
                     end  =c(11,16, rep(16+9*0:11, each=4) + c(6,7,8,9))))
  
names(temps) <- c("Station", "Year", 
                 paste0(rep(c("Value","DMflag", "QCflag", "DSflag"), 12), 
                        rep(1:12, each=4)))

temps <- temps %>% 
  gather(key="Month", value="Temp_Max", starts_with("Value"))
temps$Month <- as.numeric(gsub("Value", "", temps$Month))
temps$Temp_Max <- replace(temps$Temp_Max, 
                          temps$Temp_Max == -9999, NA)
temps$Temp_Max <- temps$Temp_Max/100
temps$YearMonth <- temps$Year+temps$Month/12
temps
}

data <- tmax("USH00011084")

head(data)

```

#### Visualizing the Data


```{r pressure, echo=FALSE}

data %>% ggplot(aes(x = YearMonth, Temp_Max, colour= Temp_Max)) + 
  geom_point()  +
  scale_color_viridis(option="B")

data %>% ggplot(aes(x = Year, Temp_Max, colour=Temp_Max)) + 
  geom_point() + facet_wrap(~Month, nrow=2) +
  scale_color_viridis(option="B")


data %>% ggplot(aes(x = Month, Temp_Max, colour=Year)) + 
  geom_point() +geom_jitter(width = 0.34)+
  scale_color_viridis(option="B")
```


